### ISSUE TITLE
Gráficos en el script de Bias Correction

### ISSUE THREAD

**Issue by cenavarror** [CIAT-DAPA/dapa-climate-change#6]
**General**
- [x] Arreglar aes por aes_string en donde sea necesario
- [x] Poner colores estándar en todos los plots
- [x] Ubicar meses en facet_grid 
- [x] Ubicar leyendas abajo en gráficos por meses
- [x] Habilitar para seleccionar varios métodos.
- [x] Colocar todos los nombres de las carpetas en minúsculas: Statistics a stats; Density a density; Indicators crear dos carpetas con condición rainy_days y hot_days.
- [x] Cambiar colores de las graficas: 
#d7191c  raw rojo (#fdae61 naranja)
#abd9e9 ch factor no variability - azul
#2c7bb6 ch factor variability -azul claro
#4dac26 qmap - verde
#a6611a bc variability - cafe
#dfc27d bc no variability - café claro
- [x] cambiar raw_merge a raw_data
- [x] separar labels del eje y
- [x] cambiar colores de cafes y azules invertir
- [x] cambiar tonalidades a los azules
- [x] Quitar "beta version" en el título de la página de BC
- [x] Hacer los cambios en el portal desde el mockup
- [x] Arreglar icons y ribbons (CN)
- [x] Cambiar el texto en el website de BC and WS (CN)
- [x] Escribir la sección de bias correction (CN)
- [x] Escribir el readme (CN)
- [x] Cambiar nombre de archivo "README.txt" por "readme.txt"
- [x] Readme debe ir dentro del comprimido \bc.zip\readme.txt
- [x] Actualizar documento de BC para publicar en sección documentation (CN)
- [x] Actualizar documento de BC (pdf) en sección documentation

**1. Timeseries:**
- [x] Corregir posición leyenda
- [x] Hacer a nivel mensual
- [x] Probar con un gráfico de medias móviles
- [x] cambiar labels eje x day y month

**2. Internal variability:**
- [x] Cambiar STD por valores absolutos y ponerlos en boxplots para ver la variabilidad
- [x] Corregir posición leyenda
- [x] cambiar titulo de gráfico quitar STD
- [x] cambiar tamaño de texto de los meses y eje y.
- [x] cambiar el alto de la gráfica a 350px.
- [x] separar un poco los métodos en la leyenda.

**3. Frequency:**
- [x] OK código
- [x] Corregir posición leyenda.
- [x] cambiar tamaño de texto de los meses y eje y.
- [x] cambiar el alto de la gráfica a 350px.
- [x] separar un poco los métodos en la leyenda.
- [x] Eliminar archivos de texto de freq 

**4. Density:**
- [x] Sacar unos índices de curtosis y asimetría para reemplazar los diarios?
- [x] Cambiarlo por uno a nivel mensual 

**5. Projected change:**
- [x] Agregar todos los métodos en una sola gráfica 
- [x] Aumentar tamaño de la leyenda
- [x] revisar srad
- [x] cambiar colores azules y cafes

**5. Cambios:**
- [x] Arreglar la ecuación BC futura (está mostrando 0 cambio)
Errado: gcm.fut.bc <- wfd.his.avg + ( (wfd.his.std / gcm.fut.std) * (gcm.fut.day.stack - gcm.fut.avg) )
Correcto: gcm.fut.bc <- wfd.his.avg + ( (wfd.his.std / gcm.his.std) * (gcm.fut.day.stack - gcm.his.avg))
- [x] cambiar tamaño de texto de los meses y eje y.
- [x] separar un poco los métodos en la leyenda.
- [x] arreglar bug cuando se sube un archivo de estación con valores NA

**Comment by cenavarror** [comment]
Texto para BC interface

The data distributed here are in text file format and are derivated from Global Climate Models (GCM) and observational datasets (Reanalysis). CCAFS and its partners have developed this on live processing to provide continuous future climate data. Users are prohibited from any commercial, non-free resale, or redistribution without explicit written permission from CCAFS or the data-developing institutions. Users should acknowledge CCAFS as the source used in the creation of any reports, publications, new data sets, derived products, or services resulting from the use of this data set. For commercial access to the data, send requests to Andy Jarvis at the International Center for Tropical Agriculture (CIAT).

Last updated: 27 June 2016

**Comment by cenavarror** [comment]
Texto para Weather stations interface

The data distributed here are in text file format from weather stations data. CCAFS and its partners have developed this on live query and download interface to provide observational data for CCAFS/CIAT/Partners related projects. Users are prohibited from any commercial, non-free resale, or redistribution without explicit written permission from CCAFS or the data-developing institutions. Users should acknowledge CCAFS as the source used in the creation of any reports, publications, new data sets, derived products, or services resulting from the use of this data set. For commercial access to the data, send requests to Andy Jarvis at the International Center for Tropical Agriculture (CIAT).
Last updated: June 2016

**Comment by cenavarror** [comment]
Texto para sección de Bias Correction: 
Disponible en \.\Dropbox\CCAFS-Climate\design\bias-correction\bc_section_description.docx
Tener en cuenta los hipervículos tanto externos como referencias dentro de la misma página. Los archivos de las imágenes están dentro de la misma carpeta.

**Comment by cenavarror** [comment]
Documento de descripción de métodos de BC (pdf) para publicar en sección Documentation:
Disponible en .\Dropbox\CCAFS-Climate\documentation\bias-correction\BC_methods_explaining_v3.pdf

**Comment by jheduart** [comment]
Aplicado los cambios http://172.22.52.48/

**Comment by cenavarror** [comment]
Modificación en el mockup ver:
.\Dropbox\CCAFS-Climate\design\mockups\mockups_ccafs_climate_new_v2.pdf

**Comment by cenavarror** [comment]
Reemplazar el header por:
.\Dropbox\CCAFS-Climate\design\pictures\img\header-01.png

**Comment by cenavarror** [comment]
Hacer cambios en la página de Eta Model (ver captura)
![capture](https://cloud.githubusercontent.com/assets/6454414/16428835/52554014-3d39-11e6-88ab-ea0cec01aff8.JPG)
- Pestaña del explorador tiene otro nombre
- Header (ribbon) cambiar por .\Dropbox\CCAFS-Climate\design\pictures\img\sin entrelazado\ribbon_header_etamodel.gif
- Cambiar subtítulo por "Dynamical Downscaling (Eta Model)"

**Comment by cenavarror** [comment]
Cambiar ribbon Bias Correction por:
.\Dropbox\CCAFS-Climate\design\pictures\img\sin entrelazado\header_bc_cinta.gif

**Comment by cenavarror** [comment]
Cambiar ribbon Weather Stations por:
.\Dropbox\CCAFS-Climate\design\pictures\img\sin entrelazado\header_ws_cinta.gif

**Comment by cenavarror** [comment]
Cambiar Ribbon Bias Correction (de la sección de Data) por: 
.\Dropbox\CCAFS-Climate\design\pictures\img\sin entrelazado\header_bc_data_cinta.gif

**Comment by cenavarror** [comment]
Cambiar submenus de data por:
![submenu-08](https://cloud.githubusercontent.com/assets/6454414/16430477/7fc89ebc-3d41-11e6-850a-c838f0868487.png)
![submenu-09](https://cloud.githubusercontent.com/assets/6454414/16430476/7fc5c50c-3d41-11e6-9e4d-06874dbb6d8c.png)
![submenu-10](https://cloud.githubusercontent.com/assets/6454414/16430475/7fc4bb30-3d41-11e6-90cb-fc6b8c6f5d52.png)

**Comment by cenavarror** [comment]
Agregar/reemplazar submenus de Spatial Downscaling y Bias correction por:
.\Dropbox\CCAFS-Climate\design\pictures\img\menus
![menu_index-05](https://cloud.githubusercontent.com/assets/6454414/16430594/f4f7acb4-3d41-11e6-843b-78fd53502083.png)
![menu_index-09](https://cloud.githubusercontent.com/assets/6454414/16430595/f51091a2-3d41-11e6-816e-3f139b4d620f.png)

**Comment by jheduart** [comment]
Actualizado, sin embargo las últimas imágenes no se donde van?

**Comment by jheduart** [comment]
listo aplicado los cambios http://172.22.52.48/
